# Generated by Django 5.0.6 on 2024-06-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redactor',
            options={'verbose_name': 'redactor', 'verbose_name_plural': 'redactors'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RenameField(
            model_name='newspaper',
            old_name='publishers',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='redactor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
