# Generated by Django 5.0.6 on 2024-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_redactor_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='redactors/'),
        ),
    ]
